// 📖 ターゲット1900 特製単語帳データ（40選）
// 今後単語を増やしたいときは、このファイルに同じルールでどんどん追加していくだけでOK！
const wordList = [
    { word: "establish", meaning: "〜を設立する、確立する" },
    { word: "maintain", meaning: "〜を維持する、主張する" },
    { word: "respond", meaning: "反応する、答える" },
    { word: "frequently", meaning: "頻繁に" },
    { word: "consequence", meaning: "結果、成果" },
    { word: "significant", meaning: "重要な、かなりの" },
    { word: "environment", meaning: "環境" },
    { word: "provide", meaning: "〜を供給する、提供する" },
    { word: "indicate", meaning: "〜を指し示す、表す" },
    { word: "manage", meaning: "〜を何とか成し遂げる、管理する" },
    { word: "purchase", meaning: "〜を購入する" },
    { word: "require", meaning: "〜を必要とする" },
    { word: "determine", meaning: "〜を決定する、決心する" },
    { word: "acquire", meaning: "〜を獲得する、習得する" },
    { word: "examine", meaning: "〜を調査する、検査する" },
    { word: "increase", meaning: "増加する、〜を増やす" },
    { word: "decrease", meaning: "減少する、〜を減らす" },
    { word: "improve", meaning: "〜を向上させる、改善する" },
    { word: "reduce", meaning: "〜を減らす、縮小する" },
    { word: "observe", meaning: "〜に気づく、〜を観察する" },
    { word: "estimate", meaning: "〜を見積もる、評価する" },
    { word: "reveal", meaning: "〜を明らかにする、暴露する" },
    { word: "emerge", meaning: "現れる、明らかになる" },
    { word: "survive", meaning: "生き残る、〜を生き延びる" },
    { word: "affect", meaning: "〜に影響を及ぼす" },
    { word: "prove", meaning: "〜を証明する、〜だと判明する" },
    { word: "allow", meaning: "〜を許す、〜を可能にする" },
    { word: "encourage", meaning: "〜を奨励する、元気づける" },
    { word: "assume", meaning: "〜と仮定する、〜を引き受ける" },
    { word: "refuse", meaning: "〜を拒む、断る" },
    { word: "avoid", meaning: "〜を避ける、回避する" },
    { word: "ignore", meaning: "〜を無視する" },
    { word: "prevent", meaning: "〜を妨げる、防ぐ" },
    { word: "compare", meaning: "〜を比較する、例える" },
    { word: "contrast", meaning: "〜を対比させる" },
    { word: "admit", meaning: "〜を認める、入会を許す" },
    { word: "deny", meaning: "〜を否定する、拒む" },
    { word: "reject", meaning: "〜を拒絶する、不合格にする" },
    { word: "accept", meaning: "〜を受け入れる、承認する" },
    { word: "require", meaning: "〜を要求する、必要とする" }
];